### ISSUE TITLE
Exception MissingMethodException: Method not found: 'PartAddModule'.

### ISSUE THREAD

**Issue by TedThompson** [linuxgurugamer/EVAParachutesAndEjectionSeats#1]
Not working.  Getting:

`Exception MissingMethodException: Method not found: 'PartAddModule'.`

Spamming the log/console when I go to launch scene.  
[output_log.txt](https://github.com/linuxgurugamer/EVAParachutesAndEjectionSeats/files/498771/output_log.txt)
[KSP.log.txt](https://github.com/linuxgurugamer/EVAParachutesAndEjectionSeats/files/498774/KSP.log.txt)

Does not happen in SPH.  Game works, but eject does nothing.

Running - Kerbal Space Program - 1.2.0.1540 (WindowsPlayer x64)-pre

(While I'm here, what's with the right click "deploy" button, does it do anything besides "turning on the lights"?)

**Comment by linuxgurugamer** [comment]
Recompile fixed it, download new version here: https://github.com/linuxgurugamer/EVAParachutesAndEjectionSeats/releases/tag/0.1.2.1
