### ISSUE TITLE
Plummeting Kerbals

### ISSUE THREAD

**Issue by TedThompson** [linuxgurugamer/EVAParachutesAndEjectionSeats#2]
This one may be KSP and not you...  Normally, a falling Kerbal slows as it descends into thicker atmo.  Some times, when my Kerbal ejects, they start accelerating toward the ground and I can't get the chute to deploy.

I right click and click both deploy buttons one at a time to attempt chute deployment.

Space+F seems to never work no matter how long I press it or when.
[KSP.log.txt](https://github.com/linuxgurugamer/EVAParachutesAndEjectionSeats/files/499632/KSP.log.txt)
[output_log.txt](https://github.com/linuxgurugamer/EVAParachutesAndEjectionSeats/files/499633/output_log.txt)

Update1: I just tried several "F9" reverts and it's happening every time so here's my save file.
[quicksave - Copy.sfs.txt](https://github.com/linuxgurugamer/EVAParachutesAndEjectionSeats/files/499645/quicksave.-.Copy.sfs.txt)
I have Porkjet's revamped parts installed and in use...  I'm ejecting a 7km on the altimeter.

Update2:  I discovered that if I use the built in EVA button and then right click and click deploy chute it works fine.

**Comment by linuxgurugamer** [comment]
When you eject, is the hatch facing up or down?

**Comment by linuxgurugamer** [comment]
Never mind, I have been able to replicate it
Not sure yet where the problem is.  The chute isn't deploying because the kerbal is descending too fast, but why that is, I don't know

**Comment by TedThompson** [comment]
It seems like the thrust applied by the "ejection seat" is stuck on and accelerating the Kerbal into the ground.

**Comment by linuxgurugamer** [comment]
fixed, thanks for the report: https://github.com/linuxgurugamer/EVAParachutesAndEjectionSeats/releases/tag/0.1.3
