### ISSUE TITLE
Partless Ejection

### ISSUE THREAD

**Issue by Bit-Fiddler** [linuxgurugamer/EVAParachutesAndEjectionSeats#3]
the proposed MM patch to add the module to every part that has crew in it.

@PART[*]:HAS[#CrewCapacity[>0]]:NEEDS[VanguardTechnologies]:Final
{
    %MODULE[ModuleKrEjectPilot]
    {
        %name = ModuleKrEjectPilot
        %ejectionForce = 100
        %baseCost = 666
        %baseMass = 0.1
        %maxUses = #$../CrewCapacity$
        %deployedDrag = 30
        %minAirPressureToOpen = 0.04
        %semiDeployedFraction = 0.25
        %semiDeployedHeight = 1.25
        %deployTime = 0.33
        %Soundfile = VanguardTechnologies/Sounds/ejectionSound
        %Volume = 1
    }
}

**Comment by linuxgurugamer** [comment]
Done in 0.1.9.
