### ISSUE TITLE
Console flood and uge FPS drop still in v.017

### ISSUE THREAD

**Issue by KubaAseph** [linuxgurugamer/EVAParachutesAndEjectionSeats#4]
I got the same in .016, althrough at least parachutes work now.
This kinda of info in console is produced in massive amount and FPS drops from +/- 50 to 4.
![20161029122740_1](https://cloud.githubusercontent.com/assets/19820244/19828912/8fd85188-9dd3-11e6-8b9f-66bcfdda98a3.jpg)

**Comment by linuxgurugamer** [comment]
Looks like some debug code stayed around, I;ll get out an update

**Comment by linuxgurugamer** [comment]
Fixed and released
